### ISSUE TITLE
PlayController Error

### ISSUE THREAD

**Issue by Aspectors** [RafaelSolVargas/Vulkan#27]
![image](https://user-images.githubusercontent.com/84977235/190630072-b2e33219-8791-4c55-846c-957d86cd8cfb.png)

**Comment by Aspectors** [comment]
this is my issue when i try to play a song
i did do the requirements and everything

**Comment by RafaelSolVargas** [comment]
Hello!

Can I know your python version? (Just type ``python --version`` in the terminal)
And the modules that are installed by your pip? (Just type ``pip list`` in the terminal)

**Comment by Aspectors** [comment]
Python version = 3.9.6
pip list = aiodns                   3.0.0
aiofiles                 0.6.0
aiohttp                  3.7.4.post0
aiosignal                1.2.0
aiosqlite                0.17.0
arabic-reshaper          2.1.3
async-generator          1.10
async-timeout            3.0.1
asyncio                  3.4.3
asyncio-extras           1.3.2
asyncpraw                7.5.0
asyncprawcore            2.3.0
asyncspotify             0.12.1
attrs                    22.1.0
av                       8.0.3
beautifulsoup4           4.9.3
Brotli                   1.0.9
brotlipy                 0.7.0
bs4                      0.0.1
cchardet                 2.1.7
certifi                  2022.6.15
cffi                     1.15.1
chardet                  4.0.0
charset-normalizer       2.1.1
colorama                 0.4.5
commonmark               0.9.1
dblpy                    0.4.0
decorator                5.1.1
deezer-python            5.3.3
defusedxml               0.7.1
Deprecated               1.2.13
discord                  1.0.1
discord-py-slash-command 3.0.3
discord.py               1.7.3
DiscordUtils             1.2.9.2
frozenlist               1.3.1
future                   0.18.2
httptools                0.4.0
idna                     2.10
isodate                  0.6.1
lxml                     4.6.3
markdownify              0.9.2
multidict                5.2.0
mutagen                  1.45.1
packaging                21.3
Pillow                   8.0.1
pip                      21.1.3
PixivPy-Async            1.2.14
praw                     7.6.0
prawcore                 2.3.0
prettytable              1.0.1
psutil                   5.8.0
py-cord                  2.0.0
pycares                  4.2.2
pycparser                2.21
pycryptodomex            3.15.0
pyfiglet                 0.8.post1
Pygments                 2.13.0
PyNaCl                   1.4.0
pyparsing                3.0.9
python-bidi              0.4.2
python-decouple          3.5
qrcode                   6.1
ratelimiter              1.2.0.post0
redis                    4.1.4
requests                 2.25.1
rich                     10.6.0
sanic                    21.6.2
sanic-routing            0.7.2
setuptools               56.0.0
six                      1.16.0
soupsieve                2.3.2.post1
spotipy                  2.19.0
timedelta                2020.12.3
typing-extensions        4.0.1
update-checker           0.18.0
urllib3                  1.26.12
validators               0.20.0
wcwidth                  0.2.5
websocket-client         1.4.1
websockets               9.1
wrapt                    1.14.1
yarl                     1.8.1
youtube-dl               2021.12.17
youtube-dlc              2020.11.11.post3
youtube-related          1.0.2
yt-dlp                   2022.3.8.2
ytpy                     2021.8.17

**Comment by Aspectors** [comment]
Thats it

**Comment by RafaelSolVargas** [comment]
I found this source talking about this error:
https://stackoverflow.com/questions/46779860/multiprocessing-managers-and-custom-classes

Later today I will try to implement some of the solutions and upload a patch for you.

**Comment by Aspectors** [comment]
ok thanks

**Comment by RafaelSolVargas** [comment]
Hello again @Aspectors.

After some research I found that this error is in the multiprocessing library, used in this project to maximize the music playback experience. This bug has been around since 2017 and took a long time to merge into Python's standard library, and your version of Python (3.9.6) doesn't have the correct native code.
So, you have two options, you can apply these small changes to the native multiprocessing file in your machine [PR code](https://github.com/python/cpython/pull/4819/commits/2cc589434d505d08978d2499f15683acfccc1405) or just update your python version for 3.10>.

My Python version is 3.10.4 and it is working properly, I will update the requirements in Vulkan to python version 3.10.
Thanks for your time reporting this issue, it means a lot to me.
If you can leave a star on this project I would appreciate it.

More information about the Python native lib error: 
https://bugs.python.org/issue30256
