### ISSUE TITLE
No module named 'discord.bot'

### ISSUE THREAD

**Issue by philipsdirk** [RafaelSolVargas/Vulkan#28]
After installing everything from the requirements.txt via pip install and running the main.py I get the following error:
![image](https://user-images.githubusercontent.com/36275545/195639715-1a8740de-7ddd-444d-abc7-52a0fd2a6899.png)

**Comment by RafaelSolVargas** [comment]
Hi!
Can you show us what the command ```pip list``` return in the terminal?

**Comment by philipsdirk** [comment]
[OUTPUT.TXT](https://github.com/RafaelSolVargas/Vulkan/files/9781081/OUTPUT.TXT)
This is the result of `pip3 list`

**Comment by RafaelSolVargas** [comment]
Your py-cord version is outdated, it must be >= 2.0 as it's showed in this image
![image](https://user-images.githubusercontent.com/86136313/195725251-652176f7-b5af-4ef0-b016-f1cf1dd503d6.png)

You can try ```sudo pip install pycord --upgrade``` as it's used in this [link](https://stackoverflow.com/questions/5183672/how-do-i-update-a-python-package).
Let me know if you got any progress!

**Comment by philipsdirk** [comment]
Never mind, the problem was with my installation of Python. Fixed that and works fine now!
