### ISSUE TITLE
Is there any way to prevent the bot from auto disconnecting

### ISSUE THREAD

**Issue by Paillat-dev** [RafaelSolVargas/Vulkan#33]
Is there a way to prevent the bot from disconnecting if there's nobody in the channel, in order to have a 24/7 bot with loop?

**Comment by RafaelSolVargas** [comment]
Yes, that's not too hard.
Just a new flag in config.py and a if in a specific function should be enough, but I have some doubts.
You would like to have the bot playing the song until the reaches the end of the playlist and only then he disconnects OR you want him to still in the voice channel 24/7, no matter if it's playing or not?
Depending on what you want, I could add this feature in 1 day.

**Comment by Paillat-dev** [comment]
What I want is having the bot playing music 24/7, simply I enable a loop=all, and just need to avoid the bot from disconnecting when there's nobody in the channel.Btw, great work, it's amazingLe 23 janv. 2023 06:07, Rafael Vargas ***@***.***> a écrit :
Yes, that's not too hard.
Just a new flag in config.py and a if in a specific function should be enough, but I have some doubts.
You would like to have the bot playing the song until the reaches the end of the playlist and only then he disconnects OR you want him to still in the voice channel 24/7, no matter if it's playing or not?
Depending on what you want, I could add this feature in 1 day.

**Comment by RafaelSolVargas** [comment]
Done!
You can see the changes in the code in this [commit](https://github.com/RafaelSolVargas/Vulkan/commit/7310eda1a1f1019f74b449a63deb5f87758b1e78).
As it's in the Readme.md, you must change a line of code to have your feature working:

```
Change the property SHOULD_AUTO_DISCONNECT_WHEN_ALONE of the VConfigs class to False
The path to the file is ./Config/Configs.py
```
If you have any question, don't mind asking.

**Comment by Paillat-dev** [comment]
Thank you very much! Great work!
