### ISSUE TITLE
Unable to extract uploader id error

### ISSUE THREAD

**Issue by atikiN589** [RafaelSolVargas/Vulkan#36]
So, when you try to download a video, the yt-dlp say: "ERROR: [youtube] GXFlILWExSY: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U".
I think this caused by youtube new "@user" url. This was fixed in last versions of YoutubeDL, but when I try to start vulkan with last version of ytdl it crashes with many errors in console.

**Comment by RafaelSolVargas** [comment]
Can you send me the specific song you are trying to download?

**Comment by atikiN589** [comment]
I`m running run_test.py

**Comment by brunoluppi** [comment]
> I`m running run_tests.py

Try: "pip install --upgrade yt-dlp -U" and try running again

**Comment by RafaelSolVargas** [comment]
As @brunoluppi told, the ```pip install --upgrade yt-dlp -U``` works, and I already patched this error by upgrading the default version of the yt-dlp library used in this project.
