### ISSUE TITLE
Music cog not loaded!!

### ISSUE THREAD

**Issue by LonelyGuy12** [RafaelSolVargas/Vulkan#38]
```json
[{'DiscordCogs.MusicCog': ExtensionFailed("Extension 'DiscordCogs.MusicCog' raised an error: TypeError: 'type' object is not subscriptable")}
```

**Comment by LonelyGuy12** [comment]
No I didn't made any changes at all....

I tried to host the bot on https://railway.app/ and it didn't work :/

**Comment by LonelyGuy12** [comment]
![image](https://user-images.githubusercontent.com/93421108/220166368-2690c493-5cf1-4fef-81d4-b99d5021af27.png)

**Comment by LonelyGuy12** [comment]
ok uhm... I tried running it locally and it actually works!
![image](https://user-images.githubusercontent.com/93421108/220167951-55e645b4-f9fd-402d-b5dc-b395e56f84d5.png)

**Comment by LonelyGuy12** [comment]
Could by any chance tell what could be the issue with the hosting and how can it be fixed?

**Comment by RafaelSolVargas** [comment]
I don't know the exactly problem, hosting a music Bot is not a easy task and is different for each plataform, i suggest you to look for youtube tutorials about hosting music bots in the plataform you want to use.

You can add this ```print(e)``` in this line inside the VulkanInitializer.py file, you will get more details about the error. I think that has something related to the way the RaillWays load the project folders.
![image](https://user-images.githubusercontent.com/86136313/220169905-067a9735-9d1e-4531-9f59-c0fb092d8c0d.png)
