### ISSUE TITLE
ERROR IN PLAY SONG FUNCTION

### ISSUE THREAD

**Issue by atikiN589** [RafaelSolVargas/Vulkan#39]
When I try to play any track with the /play command, I get this error: [ERROR IN PLAY SONG FUNCTION] -> , <class 'discord.opus.Opus.OpusNotLoaded'>.
In discord only download message appears.

**Comment by RafaelSolVargas** [comment]
Hello!
This error happened  only when you were using the slash command? Or with the default discord command as well?

**Comment by RafaelSolVargas** [comment]
I think that this error is related to the installation of FFMPEG, please verify if you has followed the instructions bellow.

**Installation of FFMPEG**
FFMPEG is a module that will be used to play music, you must have this configured in your machine FFMPEG must be configured in the PATH for Windows users. Check this [YoutubeVideo](https://www.youtube.com/watch?v=r1AtmY-RMyQ&t=114s&ab_channel=TroubleChute).

You can download the executables in this link https://www.ffmpeg.org/download.html and then put the .exe files inside a ffmpeg\bin folder in your C:\ folder. **Do not forget to add 'ffmpeg\bin' to your PATH.**

**Comment by atikiN589** [comment]
Hello, I think that my error caused because of replit. I`m running my bot there and they have preinstalled ffmpeg. 

I will try to reinstall ffmpeg there and check it again. I`ll reply if it helps.
