### ISSUE TITLE
Bug queue

### ISSUE THREAD

**Issue by mateuseduardofaria** [RafaelSolVargas/Vulkan#41]
It seems that when the queue ends the bot crashes and doesn't work anymore at least it keeps downloading the music and it never ends with that it doesn't play the music

**Comment by mateuseduardofaria** [comment]
Como vi que tu é Brasileiro basicamente ele para de funcionar depois que o bot para no caso quando a fila acaba ou quando não tem mais nenhuma música na fila

**Comment by RafaelSolVargas** [comment]
Entao basicamente se ele estiver tocando uma playlist, assim que terminar a ultima ele dá um erro? Você tem algum print do erro?

**Comment by mateuseduardofaria** [comment]
Sim, tava na playlist e quando parou a playlist o bot sumiu e não volta mais não importa o quanto eu aperte em play novamente ele não volta, fala que ta na playlist ou que está baixando mais não reproduz e o bot não volta 
![error](https://user-images.githubusercontent.com/54746895/224497879-14e084da-3b3a-43df-8eeb-e9119b7ed87e.png)
pro canal.

**Comment by RafaelSolVargas** [comment]
Eae man, foi mal a demora, tá corrido aqui a vida
Já corrigi esse erro, vlw por ter reportado ele. Qualquer coisa só criar outra issue, se puder dar uma estrela no projeto agradeço.
Tmj!

**Comment by mateuseduardofaria** [comment]
Certo meu amigo, muito obrigado! e meus parabéns pelo bot com certeza um dos melhores que já vi. Só podia ser Brasileiro pra fazer uma obra prima dessas hahaha.
