### ISSUE TITLE
No audio/sound after voice channel connection

### ISSUE THREAD

**Issue by jrdurham** [RafaelSolVargas/Vulkan#43]
**Describe your context**
Started seeing an issue yesterday where the bot would connect to a voice channel, but would not play any audio. To be certain it wasn't an isolated issue, I was able to recreate this issue on a completely clean brand new Debian installation with Python3.10.10. PIP seemed to install the necessary packages from the requirements.txt with no issues. The only changes made after cloning the repo were to update the .env file with the appropriate discord and spotify values. Aside from the .env file, no changes were made to any configs.
**The path to the bug**
Pretty simple, just issue a command such as _!play the outfield your love lyrics_. The bot does not react to the message to acknowledge the command was received successfully, but it _does_ join the appropriate voice channel. However, no audio or sound is played and the bot will sit in the channel until the script is forcibly closed with ^c.

**Screenshots**
Here is the output from the python script:

`$ python3.10 main.py`
`Starting Vulkan...`
`Vulkan is now operating.`
`Starting Player Thread for Guild MusicBotTest`
`[THREAD PLAYER -> CONNECTING TO VOICE CHANNEL]`

I don't know that I've really included any helpful information, but if you can tell me where I can get any specific information you need I'll be more than happy to snag it and drop it here.

**Comment by moenekoeth** [comment]
I am having the same issue, since about yesterday . On Python 3.9.5

**Comment by jrdurham** [comment]
Seeing as how it's not just me, I'm willing to bet this is a change on YouTube's side and we'll have to wait for yt_dlp to update to adapt to whatever the change was.

**Comment by Eric106** [comment]
Same issue here. It's not from youtube side, is an update on discord API (My bot user discord.py), since I update the library the audio come back, but need to fix other functions.

**Comment by RafaelSolVargas** [comment]
Hey guys!
As @Eric106 reported, it appears to be a pycord issue, just run the command ```pip install py-cord --upgrade``` to upgrade to pycord version 2.4.1. This resolves the reported audio issue, but the code may stop working at other points, so I'm now checking which parts of the project still work.
For now, you can run the command locally and look for other issues :)

**Comment by jrdurham** [comment]
Thanks @RafaelSolVargas, that's actually what I ended up doing right after @Eric106's reply. I'm not all too familiar with the Discord API, but thank goodness you guys are, this would've taken me a good while to figure out on my own!

**Comment by ardunaline** [comment]
Same issue here, am on 2.4.1 version of pycord.
