### ISSUE TITLE
Add Volume Feature

### ISSUE THREAD

**Issue by rivai45** [RafaelSolVargas/Vulkan#45]
Can you add volume feature, that only owner or admin can set the volume?
Discord mobile sometime have bug, that you cant set the volume from bot, or even mute/unmute, so this feature will usefull I think...

**Comment by RafaelSolVargas** [comment]
Hello @rivai45!
I'm already working on it, I'm also expecting to release a new version with this feature in this week.

**Comment by RafaelSolVargas** [comment]
Hello @rivai45 
I implemented your feature request in this commit https://github.com/RafaelSolVargas/Vulkan/commit/2114f158405bb2974ee50973989490d7422cb8bc.
This feature stills in pre-release, so if you or anyone find any problem, please feel free to report an issue in this project.

Thank you!
