### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Partymann2000** [RafaelSolVargas/Vulkan#46]
**Describe your context**
when i use /play with spotify or youtbe all configs a correte the spotify keys are corret

**The path to the bug**
[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
Starting Vulkan...
Vulkan is now operating.
Starting Player Process for Guild Xenority
[PROCESS PLAYER -> CONNECTING TO VOICE CHANNEL]
Player Process Xenority received command VCommandsType.PLAY
Process Xenority sended command VCommandsType.NOW_PLAYING
[https @ 0x564e352f5b00] HTTP error 403 Forbidden
https://rr5---sn-4g5lzned.googlevideo.com/videoplayback?expire=1687700577&ei=AfCXZKrnB9CxgQf37LHwCQ&ip=148.251.48.2&id=o-AB-j1mrF6pxNPMKqUPvnDdhSw6vRC5UwekywEzZ5gLuE&itag=251&source=youtube&requiressl=yes&mh=kw&mm=31%2C29&mn=sn-4g5lzned%2Csn-4g5edn6y&ms=au%2Crdu&mv=m&mvi=5&pl=24&gcr=de&initcwndbps=611250&spc=qEK7B9pFiShMiqHEqN28qLizBEXD1U1La7iZuRaflg&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=1683444&dur=108.721&lmt=1669743262388535&mt=1687678614&fvip=2&keepalive=yes&fexp=24007246%2C24363391&beids=24350018&c=ANDROID&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJQJtGZg9et53wpCOdT5knBmKvTtXRjciQAi5xwzkFGnAiEAqJW0E1mVWO2T5-zMY2lTYOdGJwWe1dUcEAWhSTGQK4g%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgPVhxOtMeQ8NCFQ2H5Q2s5NXcSkCRZqYmWbokaNFowh4CIAwoUIQ6kTFcCClcLXxWx6EtLcsITJI8yfjUBSp3_1zl: Server returned 403 Forbidden (access denied)
Process Xenority sended command VCommandsType.SLEEPING
Starting Player Process for Guild Xenority
[PROCESS PLAYER -> CONNECTING TO VOICE CHANNEL]
Player Process Xenority received command VCommandsType.PLAY
Player Process Xenority received command VCommandsType.RESUME
[ERROR IN PLAYHANDLER] -> Traceback (most recent call last):
  File "/home/container/Handlers/PlayHandler.py", line 33, in run
    musicsInfo = await self.__searcher.search(track)
  File "/home/container/Music/Searcher.py", line 43, in search
    raise error  # Redirect already processed error
  File "/home/container/Music/Searcher.py", line 38, in search
    raise SpotifyError(self.__messages.SPOTIFY_NOT_FOUND,
Config.Exceptions.SpotifyError
 {<class 'Config.Exceptions.SpotifyError'>}

**Comment by RafaelSolVargas** [comment]
Hi! 
For some unknown reason the API Url to play the song seems to not allow any access.
Can you type here which link you tried to pass to the Bot? 
Also, the libraries and their respective version that are installed in your pip.

You can find this list typing ```pip list``` I think.

**Comment by Partymann2000** [comment]
https://open.spotify.com/intl-de/track/7hIwg6q4VC79IsR4xmT6A1?si=5a187bd2b4fc4578
https://www.youtube.com/watch?v=PHvC2eKmk6Y

I use pterodactzl to host the bot, i dont can use pip commands but i have installed the latest packedes

**Comment by RafaelSolVargas** [comment]
Perhaps there is a limitation in hosting aplications in pterodactzl, they could be blocking some type of http access, both Urls works here in my machine and since a lot of people is using the Bot without having this problem, I can only imagine that it's up to the pterodactzl network firewall.
Can you try running the Bot in your own machine and see if access is still being denied?

**Comment by Partymann2000** [comment]
so it works on my computer but it worked a few weeks ago and i was very happy with the bot but somehow it doesn't work anymore.

**Comment by RafaelSolVargas** [comment]
That's sad, I could not find a server to host my bot yet.
