### ISSUE TITLE
Bot fails to play certain Youtube videos

### ISSUE THREAD

**Issue by Darthwayne** [RafaelSolVargas/Vulkan#47]
**Describe your context**:
Bot fails to play certain videos from Youtube. This seems to be related to copyright(?) preventing the bot from downloading the song contents. Similar to certain Youtube videos being blocked from common online Youtube to mp3/mp4 download sites. Bot works for other Youtube video links fine. I'm using a .env file for needed keys, configuration is unmodified except for the option to disconnect the bot after a certain amount of time from the voice channel when idle is enabled. Happy to provide other info.

**The path to the bug**:
After performing /play https://www.youtube.com/watch?v=cM1F9TbJhkk, the console outputs error:
```
WARNING: [youtube] Video unavailable. This video is not available
WARNING: No video formats found!
WARNING: Requested format is not available
DEVELOPER NOTE -> Failed to Extract URL https://www.youtube.com/watch?v=cM1F9TbJhkk
[ERROR IN PLAYHANDLER] -> Traceback (most recent call last):
  File "/home/container/Handlers/PlayHandler.py", line 35, in run
    raise InvalidInput(self.messages.INVALID_INPUT, self.messages.ERROR_TITLE)
Config.Exceptions.InvalidInput
 {<class 'Config.Exceptions.InvalidInput'>}
```

**Screenshots**:
![image](https://github.com/RafaelSolVargas/Vulkan/assets/115687000/2d6ea815-c736-47d4-8f12-de47679bb969)
![image](https://github.com/RafaelSolVargas/Vulkan/assets/115687000/d227a9d2-f672-4f64-b3d5-bdf8f02f7aa5)
![image](https://github.com/RafaelSolVargas/Vulkan/assets/115687000/45267dcd-0fec-4adb-b5bd-d6dbde232fb8)

**Comment by RafaelSolVargas** [comment]
![image](https://github.com/RafaelSolVargas/Vulkan/assets/86136313/2fd6c91f-8b6c-47fb-be69-2e6b2850cf30)

![image](https://github.com/RafaelSolVargas/Vulkan/assets/86136313/caa7c568-102f-41b1-a490-47596ab4ffa5)

The Bot downloaded and played this song without any problems here. Perhaps there is a limitation of country, as this video is may not available in your location, i don't know

**Comment by RafaelSolVargas** [comment]
Considering you haven't returned any response, I'm closing this issue.
If you have any new information about this or any other issue, feel free to open another issue.
