### ISSUE TITLE
Add autoplay?

### ISSUE THREAD

**Issue by akitell** [RafaelSolVargas/Vulkan#50]
Have plan to add autoplay? Great bot!

**Comment by RafaelSolVargas** [comment]
Hi! Thanks for the issue.
Can you explain what exactly do you want with this feature?

**Comment by akitell** [comment]
This feature would enable playing random songs. For example, there are some bots that, if you play a pop song and run the "autoplay" command, it starts playing related songs automatically, without the need to add the songs manually. Is nice feature.  Thanks.

**Comment by RafaelSolVargas** [comment]
Ok, I'll see what I can do
