### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Raviexthegod** [RafaelSolVargas/Vulkan#54]
**Describe your context**
I'm using default configuration with status changed and help name changed, keeping links to bot source.

**The path to the bug**
Whenever I play a song, I don't get any audio even though I made sure my py-cord is up to date and I'm only using spotify or youtube. I also reinstalled py-cord to be sure it wasn't a broken install.

**Screenshots**
Screenshots of the error thrown or the Bot messages will help us to fix you issue faster.
![Screenshot 2023-08-12 181055](https://github.com/RafaelSolVargas/Vulkan/assets/79181275/fd5e9e98-a438-44e2-ad5d-b07f2f3db1cf)
![Screenshot 2023-08-12 181130](https://github.com/RafaelSolVargas/Vulkan/assets/79181275/f26562db-54a7-40ce-954a-7a83d1d1c1b6)

**Comment by Raviexthegod** [comment]
I found the error. Whatever I did to customize it broke the bot.

**Comment by RafaelSolVargas** [comment]
No problem, thanks for using it!
