### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by darnells68** [RafaelSolVargas/Vulkan#56]
I think the bot is now broken. It has been working very well with no issues but now if you try to play something the bot will join but no audio output im guessing its not getting audio now maybe youtube changed something. Regardless the core functionality works but the bot can no longer play any audio from youtube.

**Comment by RafaelSolVargas** [comment]
Hello!
Take a look at this issue: https://github.com/RafaelSolVargas/Vulkan/issues/55

I hope this helps
