### ISSUE TITLE
Bot searches for YT Song instead of actually playing the one on Spotify.

### ISSUE THREAD

**Issue by Rikkuzen** [RafaelSolVargas/Vulkan#60]
Simple question/issue I got.

I want to play spotify playlists and songs but instead of playing the actual spotify versions it searches for YT versions instead.
![Vulkan](https://github.com/RafaelSolVargas/Vulkan/assets/25876789/840bd905-35c4-467f-a415-e2ea7406f17d)

**Comment by Paillat-dev** [comment]
> Simple question/issue I got.
> 
> I want to play spotify playlists and songs but instead of playing the actual spotify versions it searches for YT versions instead. ![Vulkan](https://private-user-images.githubusercontent.com/25876789/289662472-840bd905-35c4-467f-a415-e2ea7406f17d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDAwMzMsIm5iZiI6MTcwMjUzOTczMywicGF0aCI6Ii8yNTg3Njc4OS8yODk2NjI0NzItODQwYmQ5MDUtMzVjNC00NjdmLWE0MTUtZTJlYTc0MDZmMTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA3NDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMzkxMmE0OTZhMTAyZTZiOWY4NmU5MGE0YWU3ZDc2ODVmMDgxMGFjM2QyM2YzYTE4OWM2ZTA0MjZlMTRkYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PGh025mraG8Y7w3xH18Je07qaDNzckEqOZj6GDlhZLo)

This is expected behaviour, not a bug. It is way harder to stream from spotify than from youtube, and maaany discord bots work this way.

**Comment by RafaelSolVargas** [comment]
I appreciate @Paillat-dev 's response, which describe correctly the context of Discord music bots.
If you have an alternative approach for streaming songs directly from Spotify, @Rikkuzen, please share relevant code snippets, or create an PR introducing the modifications required to add this behavior.
I'll be happy to implement it.
