### ISSUE TITLE
bot not showing music commands

### ISSUE THREAD

**Issue by deaduserbot18** [RafaelSolVargas/Vulkan#61]
**Describe your context**
The Vulkan contains some configuration parameters set up in the Configs/Config.py file, tell us what values you are using.
everything is default only removed spotify clint id and secret line

**The path to the bug**
Don't forget to specify how you found the issue, what Discord commands you used and which was the parameters passed.
when i try to give command to the bot i cant play songs screenshot attached 
**Screenshots**
Screenshots of the error thrown or the Bot messages will help us to fix you issue faster.
![photo_2024-01-10_16-47-26](https://github.com/RafaelSolVargas/Vulkan/assets/74369577/c3b29d52-4e48-4aa8-b340-2f2a2cd6a2eb)

**Comment by Kavex** [comment]
Most likely the prefix you are using because I have yet to have any issue that. Try changing the prefix to m! and see if you still have the same issue.

**Comment by RafaelSolVargas** [comment]
It's possible that you are facing an error when loading the Music Commands, if that is the case, then you will see an output with the error, and it's the output that we need to see
