### ISSUE TITLE
When I try to queue a Spotify playlist it doesn't work...

### ISSUE THREAD

**Issue by GameDesignerOfficial** [RafaelSolVargas/Vulkan#62]
![image](https://github.com/RafaelSolVargas/Vulkan/assets/93928812/effba164-c5e5-4356-a474-1333688dd7bd)

This is what happens ^^^

My python version:
3.11.5

My pip list:
Package                   Version
------------------------- -----------
aiohttp                   3.8.3      
aiosignal                 1.3.1      
altgraph                  0.17.3     
annotated-types           0.6.0      
ansicon                   1.89.0     
anyio                     3.7.1      
async-timeout             4.0.2      
asyncio                   3.4.3      
attrs                     22.2.0     
autopep8                  2.0.1      
beautifulsoup4            4.12.2     
blessed                   1.20.0     
Brotli                    1.0.9      
certifi                   2022.12.7  
cffi                      1.15.1     
charset-normalizer        2.1.1      
chess                     1.10.0     
click                     8.1.7      
cloc                      0.2.5      
colorama                  0.4.6      
colored                   2.2.3      
dacite                    1.8.1      
deezer-python             5.3.3      
Deprecated                1.2.14     
discord.py                2.3.2      
fastapi                   0.103.2
ffmpeg-python             0.2.0
frozenlist                1.3.3
future                    0.18.3
h11                       0.14.0
httpcore                  0.18.0
httpx                     0.25.0
idna                      3.4
imageio-ffmpeg            0.4.8
inquirer                  3.1.4
iso8601                   2.0.0
jaconv                    0.3.4
jinxed                    1.2.1
markdown-it-py            3.0.0
mdurl                     0.1.2
multidict                 6.0.4
mutagen                   1.46.0
numpy                     1.24.1
omdb                      0.10.1
packaging                 23.2
pefile                    2023.2.7
Pillow                    10.1.0
pip                       23.3.1
platformdirs              3.11.0
psutil                    5.9.6
py-cord                   2.5.0
pycodestyle               2.10.0
pycparser                 2.21
pycryptodomex             3.16.0
pydantic                  2.6.3
pydantic_core             2.16.3
Pygments                  2.17.2
pyinstaller               6.1.0
pyinstaller-hooks-contrib 2023.8
pykakasi                  2.2.1
PyNaCl                    1.5.0
python-chess              1.999
python-dateutil           2.9.0.post0
python-decouple           3.5
python-dotenv             1.0.1
python-editor             1.0.4
python-slugify            8.0.4
pytube                    15.0.0
pywin32                   306
pywin32-ctypes            0.2.2
PyWinBox                  0.3
PyWinCtl                  0.0.44
rapidfuzz                 3.6.1
readchar                  4.0.5
redis                     5.0.0
requests                  2.28.2
rich                      13.7.1
setuptools                69.1.1
six                       1.16.0
sniffio                   1.3.0
soundcloud-v2             1.3.1
soupsieve                 2.5
spotdl                    4.2.4
spotipy                   2.19.0
starlette                 0.27.0
syncedlyrics              0.7.0
text-unidecode            1.3
tomli                     2.0.1
ttkbootstrap              1.10.1
twitchio                  2.8.1
typing_extensions         4.0.1
Unidecode                 1.3.8
urllib3                   1.26.14
uvicorn                   0.23.2
wcwidth                   0.2.12
websockets                10.4
wrapt                     1.16.0
yarl                      1.8.2
youtube-search-python     1.6.6
yt-dlp                    2023.2.17
ytmusicapi                1.5.4

**Comment by GameDesignerOfficial** [comment]
This issue is solved however there is a new issue:
![image](https://github.com/RafaelSolVargas/Vulkan/assets/93928812/50291736-57b8-4c28-b218-9311dd12cceb)

**Comment by RafaelSolVargas** [comment]
Hi, thanks for using this project.
That second error that you are facing is a simple Python error when the system tries to filter the input that you are giving to it.
Show me how you are calling the play command

**Comment by RafaelSolVargas** [comment]
I'm closing this issue due to it's inactivity, but if you need you can continue commenting here @GameDesignerOfficial
