### ISSUE TITLE
Improper token has been passed

### ISSUE THREAD

**Issue by MarthexPS** [RafaelSolVargas/Vulkan#67]
add the token to the .env file, but I keep getting that error, and spotify doesn't start either

**Comment by RafaelSolVargas** [comment]
Which error are you talking about? Can you show any screenshots with the error?

**Comment by MarthexPS** [comment]
![imagen](https://github.com/RafaelSolVargas/Vulkan/assets/165730437/6a34e607-1a13-4872-bdd0-a9aa4964ff66)
It already works but it doesn't have any music command
![imagen](https://github.com/RafaelSolVargas/Vulkan/assets/165730437/ed5b45dd-a698-4bf8-9f13-65f787dae919)

**Comment by RafaelSolVargas** [comment]
If you read the log that your receiving when calling the main.py, there is a error that was raised by the python when it's was loading the MusicCog, the module that loads all Music commands, the error was "No module named 'deezer'", that means that you doesn't have all dependencies installed in your pip.
You can see the libraries that you have installed with the command
```pip list```

Take another look into the instructions that I inserted in the [README](https://github.com/RafaelSolVargas/Vulkan/blob/master/README.md) which show how to install the dependencies

**Comment by RafaelSolVargas** [comment]
I'm closing this issue as completed due to not being found any problem with the project, if you have any concerns, please feel free to comment here
